### ISSUE TITLE
Issue with "Click me" button for offer alert

### ISSUE THREAD

**Issue by rohitjoshi6** [tejasmorkar/practicals-hub#4]
1. Displaying Multiple offer upon clicking "Click me" button.
2. Unable to copy the JSON object in alert box.

**Comment by bananafondue** [comment]
Will fix it

**Comment by tejasmorkar** [comment]
Prompt can be replaced with SweetAlert2.

**Comment by rohitjoshi6** [comment]
I tried using SweetAlert for it and here are the results:

![image](https://user-images.githubusercontent.com/56406787/107532054-79ca9580-6be3-11eb-9f3d-967150fb4b74.png)


May I go ahead and create a PR?

**Comment by tejasmorkar** [comment]
> May I go ahead and create a PR?

Sure @rohitjoshi6
